version: "3.7"
services:
  reverse-proxy:
    image: "traefik:v2.1.6"
    container_name: "traefik"
    command: --log.level=ERROR --api.insecure=true --providers.docker=true --providers.docker.exposedbydefault=false --entrypoints.web.address=:80
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
  api:
    image: node:10.24.1-alpine
    user: node
    working_dir: "/apinode2"
    restart: always
    ports:
      - "3050:3050"
      - "8888:8888"
    volumes:
      - ./:/apinode2

    command: "${COMMAND_RUN_NODE}"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.router0.rule=Host(`${APP_HOST}`)"
      - "traefik.http.middlewares.test-stripprefix.stripprefix.prefixes=/api"
      - traefik.http.services.api.loadbalancer.server.port=3050
    env_file:
      - .env
